# Generated by Django 3.2 on 2022-04-13 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dossie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "birthday",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Nascimento"
                    ),
                ),
                (
                    "date_insc",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de inscrição",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Endereço"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "tel1",
                    models.CharField(
                        help_text="Telefone 1 do cliente",
                        max_length=11,
                        unique=True,
                        verbose_name="Telefone (1)",
                    ),
                ),
                (
                    "tel2",
                    models.CharField(
                        blank=True,
                        help_text="Telefone 2 do cliente",
                        max_length=11,
                        null=True,
                        unique=True,
                        verbose_name="Telefone (2)",
                    ),
                ),
                (
                    "insta",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Instagram"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
