# Generated by Django 3.2 on 2022-04-14 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossie",
            name="birthday",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="dossie",
            name="date_insc",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Data de inscrição"
            ),
        ),
    ]
