# Generated by Django 3.2 on 2022-04-14 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220414_1505"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossie",
            name="date_insc",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Data atual<built-in method today of type object at 0x00007FFDB8CBA870>",
                verbose_name="Data de inscrição",
            ),
        ),
    ]
