# Generated by Django 3.2 on 2022-04-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_dossie_date_insc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossie",
            name="date_insc",
        ),
    ]
