# Generated by Django 3.2 on 2022-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_dossie_date_insc"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossie",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Rio de Janeiro"),
                    (2, "São Paulo"),
                    (3, "Minas Gerais"),
                    (4, "Paraná"),
                ],
                default=1,
                verbose_name="Estado",
            ),
        ),
    ]
