# Generated by Django 3.2 on 2022-04-15 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_dossie_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paramsuser",
            options={"verbose_name": "Parametro", "verbose_name_plural": "Parametros"},
        ),
        migrations.AddField(
            model_name="paramsuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
