# Generated by Django 3.2 on 2022-04-15 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220415_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossie',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Nascimento'),
        ),
    ]
